blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns = [
    url(r'^$',views.mainpage,name='mainpage'),
    url(r'^mainpage.html',views.mainpage,name='forget'),
    url(r'^post/(?P<pk>[0-9]+)/$',views.post,name='post'),
    #url(r'^$',views.index,name='index'),
    #url(r'^post/(?P<pk>[0-9]+)/$',views.detail,name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.category,name='category'),
    url(r'about.html',views.about,name='about'),
    url(r'post/(?P<pk>[0-9]+)/like',views.like,name='like')

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'',include('search.urls')),
    url(r'',include('comment.urls'))

]

comment/urls.py
from django.conf.urls import url
from . import views

app_name='comment'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),

]

templates/forget/category.html
{% extends 'forget/forget.html'%}
{% block content%}
<div id="content" class="clearfix">
    <section id="primary">
        <div class="main" id="thumbs">
            {% for post in post_list%}
            {% include 'forget/miniarticle.html'%}
            {% empty%}
            {% endfor%}
            <div class="pagination">
	        </div>
        </div>
    </section>
</div>
{% endblock%}

templates/forget/comment-area.html
<section class="comment-area" id="comment-area">
    <hr>
    <h3>评论区</h3>
    <form class="commentForm" action="{% url 'comment:post_comment' post.pk %}">
        <input name="name" class="form-control " placeholder="昵称:(*)">
        <input name="email" class="form-control " placeholder="email:(*)">
        <textarea name="text" class="form-control"  placeholder="评论:(*)"></textarea>
        <input type="hidden" name="parent">
        <!--<input type="hidden" name="ifparent" value="1">-->
        <button type="button" class="submit-btn btn">提交</button>
        <span style="padding-left:25px;">评论经审核通过后展示</span>
    </form>


    <div class="comment-list-panel">
        <h4>评论列表，共 <span>{{post.comment_num}}</span> 条评论</h4>
        <div class="comment-list list-unstyled">
            {% for c in comment_list%}
            <div>

                {% if c.ifparent%}
                {% include 'forget/comment-text.html' with comment=c%}
                <div class="reply-form" style="display:none">
                    {% include 'forget/reply-form.html' with comment=c%}
                </div>
                <div class="comment-reply">
                    <button class="reply-btn">回复</button>

                </div>
                <ul class="comment-list ">
                    {% for cc in c.children.all|dictsort:'create_time'%}

                    <li style="margin-left:12px">
                        <strong>{{cc.name}}：</strong>{{cc.text}}
                    </li>
                    {% endfor%}
                </ul><br/>
                {%endif%}

            </div>
            {% empty%}
            暂无评论
            {% endfor%}

        </div>
    </div>
</section>
<script>

</script>

templates/forget/comment-text.html
<li class="comment-item">
    <strong >{{comment.name}} &bull; </strong>
    <time class="submit-date" >{{ comment.create_time }}</time>
</li><br/>
<div class="comment-text">
        {{comment.text}}
</div>

templates/forget/forget.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}

<html>
<head>
    {% get_site_info as site%}
    <title>{{site.title}}</title>
    <!-- theme forget transplanted from Wordpress theme forget-->

    <meta name="viewport" content="initial-scale=1.0,user-scalable=no">

    <link rel="stylesheet" href="http://apps.bdimg.com/libs/bootstrap/3.3.4/css/bootstrap.min.css" >
    <link rel='stylesheet' href="{% static 'admin/forget/css/main.css' %}" type='text/css' media='screen' id='css-css'/>
    <script type='text/javascript' src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>

</head>

<body>
    <header class="l-header" style="background-image:url({% static 'admin/forget/img/header.jpg'%});">
        <div class="hdbg"></div>
        <div class="hdbg2"></div>
        <div class="m-about">
            <div id="logo">
                <a href="/" >
                    <img src="{{site.logo}}"></a>
            </div>
            <h1 class="tit"><a href="/"></a></h1>
            <div class="about"></div>
        </div>
    </header>
    <div id="m-nav" class="m-nav ">
        <div id="author" class="m-nav-all">
            <div class="m-logo-url">
                <a href="about.html"><img src="{{site.logo}}"></a>
                <h3>{{site.owner}}</h3>
            </div>
            <ul class="nav">
                <div class="menu"></div>
            </ul>
        </div>
        <div id="blog_info" class="m-nav-all">
            <ul class="artist-data">
                {% get_blog_data as data%}
                <li><strong>{{data.post_num}}</strong>
                    <span class="label">文章</span></li>
                <li><strong>{{data.total_comments}}</strong>
                    <span class="label">评论</span></li>
                <li class="last"> <strong>{{data.total_views}}</strong>
                    <span class="label">浏览量</span></li>
            </ul>
        </div>
        <div id="recent_posts" class="bar">
                <h4 >近期文章</h4>
                {% get_recent_posts 3 as posts %}
                <ul>
                    {% for post in posts%}
                    <li class="post"><a href="{{post.get_absolute_url}}"><span class="title"> {{post.title}}</span></a></li>
                    {% endfor %}
                </ul>
        </div>
        <div id="contact" class="bar">
            <p>Email:</p>
            <a href="mailto:{{site.email}}">{{site.email}}</a>
        </div>
    </div>
    <div class="index-search">
        <form role="search" method="get" id="search-form" action="/search/">
            <div class="search-form">
                <span id="search-form-close">&times;</span>
                <input placeholder="Search for" type="text" value="" name="q" id="search-input-s" />
                <input type="submit" class="webFont" id="searchsubmit" value="搜索" />
            </div>
        </form>
    </div>
    <div id="m-header" class="m-header " style="position: fixed;">
        <div id="showLeftPush" class="left m-header-button"></div>
        <h1><a href="/">{{site.owner}}</a></h1>
        <div id="search-trigger" style="font-size: 18px;" class="right m-header-search"></div>
    </div>
    <div id="m-container" class="container" style="top: 40px;" >
        <aside class="sidebar">
            <div class="cbl-logo">
                <div class="cbl-logo-info">
                    <h3><a href="/">{{site.owner}}</a></h3>
                    <div class="cbl-logo-like">
                        <a href="javascript:;" data-action="ding" data-id="676767" class="favorite">
                            <span class="c-like-text">关注</span>
                            <span> | </span>
                            <span class="count">12</span>
                        </a>
                    </div>
                    <ul class="artist-data">
                        {% get_blog_data as data%}
                        <li><strong>{{data.post_num}}</strong> <span class="label1">文章</span></li>
                        <li><strong>{{data.total_comments}}</strong> <span class="label1">评论</span></li>
                        <li class="last"><strong>{{data.total_views}}</strong> <span class="label1">浏览量</span></li>
                    </ul>
                </div>
            </div>
            <div class="m-sidebar">
                <section class="topspaceinfo">
                    <h1></h1>
                    <p></p>
                </section>
                <div class="userinfo">
                    <p class="q-fans">公告： {{site.anc}}    </p>
                </div>
                <div class="cbl-tag">
                    <div class="cbl-head">热门话题</div>
                    {% get_tags as tags%}
                    <div class="items">
                        {% for tag in tags%}
                        <div class="tags-list">
                            <div class="tags-icon pull-left">{{tag.name}}</div>
                            <div class="tags-con">
                                <h3><a href="#">{{tag.name}}</a></h3>
                                <p>{{tag.num_posts}} 篇文章</p>
                            </div>
                        </div>

                        {% empty%}
                        暂无话题
                        {% endfor%}
                    </div>
                </div>
                <!--<div class="cbl-comment">-->
                    <!--<div class="cbl-head">-->
                    <!--热门评论-->
                    <!--</div>-->
                    <!--<ul></ul>-->
                <!--</div>-->
                <section class="widget widget_search">
                    <form role="search" method="get" id="searchform" action="/search/" class="form-inline">
                        <div class="input-group">
                            <input type="text" placeholder="搜索" class="form-control" name="q">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" id="search-btn" type="submit">搜索</button>
                            </span>
                        </div><!-- /input-group -->
                    </form>
                </section>
                <section class="widget widget_recent_entries">
                    <h2 class="widget_tit">近期文章</h2>
                    {% get_recent_posts as posts %}
                    <ul>
                        {% for post in posts%}
                        <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
                        {% endfor %}
                    </ul>

                </section>
                <!--<section class="widget widget_recent_comments">-->
                    <!--<h2 class="widget_tit">近期评论</h2>-->
                    <!--<ul id="recentcomments"></ul>-->
                <!--</section>-->
                <section class="widget widget_archive">
                    <h2 class="widget_tit">文章归档</h2>
                    {% get_archives as Archive%}
                    <ul>
                        {% for date in Archives%}
                        <li><a href="{% url 'blog:archives' date.year date.month %}">
                                  {{ date.year }} 年 {{ date.month }} 月</a></li>
                        {% empty %}
                        <li > 暂无归档！</li>
                        {% endfor %}
                    </ul>
                </section>
                <section class="widget widget_categories">
                    <h2 class="widget_tit">分类目录</h2>
                    {% get_categories as categories%}
                    <ul>
                        {% for cat in categories%}
                        <li class="cat-item cat-item-1">
                            <a href="{% url 'blog:category' cat.pk %}">{{cat.name}}({{cat.num_posts}})</a></li>
                        {% empty%}
                        暂无话题
                        {% endfor%}
                    </ul>
                </section>
            </div>
        </aside>

        {% block content%}
        {% endblock %}
        {% block search%}
        {% endblock%}
    </div>

    <footer id="m-footer">
        <div class="Copyright">
            <p class="copyright">&copy;  - <a href="about.html"> {{site.footer}}</a></p>
        </div>
    </footer>
<script type='text/javascript' src="{% static 'admin/forget/js/functionall.js'%}"></script>
<script type='text/javascript'>
/* <![CDATA[ */
var fashao = {"url":"#","ajaxurl":"#","postid":"#"};
/* ]]> */</script>


<script type='text/javascript' src="{% static 'admin/forget/js/myjs.js' %}"></script>

</body>
</html>

templates/forget/mainpage.html
{% extends 'forget/forget.html'%}
{% load staticfiles %}
{% block content%}
<div id="content" >       
            {% for post in posts%}
            {% include 'forget/miniarticle.html'%}
            {% empty%}
            {% endfor%}
            <div class="pagination">
	        </div>     
</div>
{% endblock%}

templates/forget/miniarticle.html
{% load staticfiles %}
<article id={{post.pk}} class="post-article ">
    <div class="author">
        <a class="author-pic"><img class="author-pic" src="{% static 'admin/forget/img/logo.jpg' %}"></a>
        <span class="author-name" >{{post.author}}</span> 

        <span class="post-time"><time >{{post.create_time}}</time></span>
    </div>
    <div>
        <a class="post-cover" href="{{post.get_absolute_url}}" style="background-image: url('{{post.cover_pic}}'); height:133px; "></a>
    </div>
    <h2 class="mini-title"><a class="slow" href="{{post.get_absolute_url}}" title="{{post.title}}">{{post.title}}</a></h2>
    <span class="tags">
        {% for tag in post.tags.all%}
        <a class="tag" href="#" rel="tag">{{tag.name}}</a>
        {%endfor%}
    </span>
    <ul class="text">
        <a href="{{post.get_absolute_url}}">{{post.excerpt}}</a>
    </ul>
    
    <div class="textfoot">
        
        <a><img src="{% static 'admin/forget/img/view.png' %}">{{post.views}}  </a>
        <a><img src="{% static 'admin/forget/img/comment.png' %}">{{post.comment_num}} </a>
        <a class="like" ><img class="like-img" src="{% static 'admin/forget/img/like.png' %}">{{post.likes}} </a>
    </div>
</article>

templates/forget/minipost.html
 <dl>
    <dt class="artitle_author_date">
    <div class="zjj_author_avatar z">
        <a href="/home.php?mod=space&amp;uid=384164&amp;do=profile"><img src="/uc_server/avatar.php?uid=384164&amp;size=middle"  ></a>
    </div>
    <div class="z">
        <div class="cr_author">安若浅溪</div>
        <div class="portallist_cat cr_3"> <a href="/portal.php?mod=list&amp;catid=3">手机</a></div>
    </div>
    <div class="article_date y">12 分钟前</div>

    </dt>
    <dd class="m"><a class="article-img" href="article-25187-1.html"
                     style="background-image: url('http://s1.dimageView2/2/w/960/q/100');"></a></dd>        
    <dt class="zjj_title"><a href="article-25187-1.html">「搞机故事」纪念曾经的手机们</a></dt>
    <dd class="cr_summary">愿你我在生活的压力下，</dd>
    <dd class="cl cr_mmtre"> 
        <span class="cr_replies">16</span>
        <span class="cr_recommend_add">1</span>
    </dd>
</dl>

templates/forget/post-like.html
<a data-action="ding" class="favorite">
    <span class="p-like-text">喜欢</span>
    <span> | </span>
    <span class="count">{{likes}}</span>
</a>

templates/forget/post.html
{% extends 'forget/forget.html'%}
{% block content%}
{% load blog_tags %}
<div id="content" class="clearfix">
	<section id="primary">
		<div class="main">
			<article class=" post-article  ">
                <img src="{{post.cover_pic}}" style="width: 100%;">
                <h1 class="title"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h1>
                <div class="text-info">
                    <div >
                        <a href="{{post.category.get_absolute_url}}">{{post.category}} &bull;</a>
                        <a >{{post.author}} &bull;</a>
                        {{post.create_time}}
                    </div>
                    modified on:{{post.modify_time}}
                </div>
                <div class="text">
                    <div >
                        {{post.body|safe}}
                    </div>
                    <div class="warning">
                        <div class="box-content">本博客所有文章如无特别注明均为原创。<br>
                            复制或转载请以超链接形式注明转自<a href="/">阿刁</a>，原文地址《<a href="{{post.get_absolute_url}}" rel="bookmark" title="{{post.title}}">{{post.title}}</a>》
                        </div>
                    </div>
                    <div class="tags">
                        <span>标签：
                            {% for tag in post.tags.all%}
                            <a href="#" class="tag">{{tag.name}}</a>
                            {%endfor%}
                        </span>

                    </div>
                    <div class="post-like" rel="">
                        <a data-action="ding" class="favorite">
                            <span class="p-like-text">喜欢</span>
                            <span> | </span>
                            <span class="count">{{post.likes}}</span>
                        </a>
                    </div>
                </div>
            </article>

            {% include 'forget/comment-area.html'%}
        </div>
	</section>
</div>
<script>

</script>
{% endblock%}

templates/forget/reply-form.html
<form class="commentForm" action="{% url 'comment:post_comment' post.pk %}">
    <input name="name" class="form-control " placeholder="昵称:(*)">
    <input name="email" class="form-control " placeholder="email:(*)">
    <textarea name="text" class="form-control"  placeholder="回复{{comment.name}}"></textarea>
    <input type="hidden" name="parent" value="{{comment.pk}}">
    <!--<input type="hidden" name="ifparent" value="0">-->
    <button type="button" class="submit-btn btn" >提交</button>
    <span style="padding-left:25px;">评论经审核通过后展示</span>
</form>

templates/forget/reply.html
<form action="{% url 'comment:post_comment' post.pk %}" method="post" >
    <div >
        <input name="name" class="form-control " placeholder="昵称:(*)">
    </div><br/>
    <div >
        <input name="email" class="form-control " placeholder="email:(*)">
    </div><br/>
    <div >
        <textarea name="text" class="form-control"  placeholder="回复{{comment.name}}"></textarea>
    </div>
    <div >
        <input type="hidden" name="parent" value="{{comment.pk}}">
        <button type="submit" class="btn btn-primary">提交</button>
        <span style="padding-left:25px;">评论经审核通过后展示</span>
    </div>

</form>